//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS201724112134
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equip
    {
        public string Eqm_id { get; set; }
        public string Eqm_name { get; set; }
        public string Eqm_standard { get; set; }
        public string Eqm_picture { get; set; }
        public Nullable<double> Eqm_price { get; set; }
        public Nullable<System.DateTime> Eqm_buydatetime { get; set; }
        public string Eqm_place { get; set; }
        public string Eqm_person { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Images Images { get; set; }
    }
}
